name: recomendou_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0  
  provider: ^6.1.1
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.1
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  intl: ^0.20.2
  cloud_functions: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
