// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBh8QGDwSFgGRSmx-pXnILy8UR0bq2mqY',
    appId: '1:486405857661:web:6ac3b490ee556447762c14',
    messagingSenderId: '486405857661',
    projectId: 'recomendou-66796',
    authDomain: 'recomendou-66796.firebaseapp.com',
    storageBucket: 'recomendou-66796.firebasestorage.app',
    measurementId: 'G-MN3LBLKPN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhfp4jtqQxDQRNYluSP5Ff45g3YKC5UY',
    appId: '1:486405857661:android:14d06a81aaf090c3762c14',
    messagingSenderId: '486405857661',
    projectId: 'recomendou-66796',
    storageBucket: 'recomendou-66796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRUqV4_jyw033LHCH-YXYdTh86elAqRc',
    appId: '1:1094345893699:ios:68c4e7a8664a140afb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    iosBundleId: 'com.example.recomendouFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcRUqV4_jyw033LHCH-YXYdTh86elAqRc',
    appId: '1:1094345893699:ios:68c4e7a8664a140afb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    iosBundleId: 'com.example.recomendouFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBh8QGDwSFgGRSmx-pXnILy8UR0bq2mqY',
    appId: '1:486405857661:web:10a790a74c795799762c14',
    messagingSenderId: '486405857661',
    projectId: 'recomendou-66796',
    authDomain: 'recomendou-66796.firebaseapp.com',
    storageBucket: 'recomendou-66796.firebasestorage.app',
    measurementId: 'G-HT72VN3WFH',
  );

}