// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1KsiPfSFyAj3krjXqniKz1TdYpl3oLh4',
    appId: '1:1094345893699:web:891461261c6963a3fb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    authDomain: 'recomendou-7067d.firebaseapp.com',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    measurementId: 'G-36CTVLJ2ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsrYsyVYB59S3Tg4R0ZQLy4nJVzG663I',
    appId: '1:1094345893699:android:a179805b29a04177fb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRUqV4_jyw033LHCH-YXYdTh86elAqRc',
    appId: '1:1094345893699:ios:68c4e7a8664a140afb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    iosBundleId: 'com.example.recomendouFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcRUqV4_jyw033LHCH-YXYdTh86elAqRc',
    appId: '1:1094345893699:ios:68c4e7a8664a140afb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    iosBundleId: 'com.example.recomendouFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1KsiPfSFyAj3krjXqniKz1TdYpl3oLh4',
    appId: '1:1094345893699:web:737c32b8de1cf6cbfb31f6',
    messagingSenderId: '1094345893699',
    projectId: 'recomendou-7067d',
    authDomain: 'recomendou-7067d.firebaseapp.com',
    storageBucket: 'recomendou-7067d.firebasestorage.app',
    measurementId: 'G-VZ8JMNT6QZ',
  );
}
